# Makefile generated by imake - do not edit!

# ----------------------------------------------------------------------
# Makefile generated from "Imake.tmpl" and <Imakefile>
# $Xorg: Imake.tmpl,v 1.4 2000/08/17 19:41:46 cpqbld Exp $
# $XdotOrg: xc/config/cf/Imake.tmpl,v 1.9 2005/01/24 06:37:31 daniels Exp $
#
#
#
#
# $XFree86: xc/config/cf/Imake.tmpl,v 3.155 2003/12/24 18:58:41 dickey Exp $
# ----------------------------------------------------------------------

all::

.SUFFIXES: .i

# $XdotOrg: xc/config/cf/Imake.cf,v 1.7 2005/03/02 11:20:29 gisburn Exp $
# $Xorg: Imake.cf,v 1.4 2000/08/17 19:41:45 cpqbld Exp $

# $XFree86: xc/config/cf/Imake.cf,v 3.88 2003/12/16 21:30:21 herrb Exp $

# -----------------------------------------------------------------------
# site-specific configuration parameters that need to come before
# the platform-specific parameters - edit site.def to change

# site:  $TOG: site.sample /main/r64_final/1 1998/02/05 16:28:49 kaleb $

# site:  $XFree86: xc/config/cf/site.def,v 3.24 2000/06/25 20:17:29 dawes Exp $

# ----------------------------------------------------------------------
# platform-specific configuration parameters - edit NetBSD.cf to change

# platform:  $Xorg: NetBSD.cf,v 1.3 2000/08/17 19:41:46 cpqbld Exp $

# platform:  $XFree86: xc/config/cf/NetBSD.cf,v 3.122 2003/11/18 18:09:45 dawes Exp $

# operating system:  NetBSD/amd64 10.1_STABLE OSBinaryType (10.1.1)

# $Xorg: bsdLib.rules,v 1.3 2000/08/17 19:41:47 cpqbld Exp $

# $XFree86: xc/config/cf/bsdLib.rules,v 3.27 2003/11/20 00:41:37 dawes Exp $

INSTALLMINORREV = true

# $XdotOrg: xc/config/cf/xorg.cf,v 1.44 2005/01/27 03:50:46 ajax Exp $

# $Xorg: xfree86.cf,v 1.4 2000/08/17 19:41:49 cpqbld Exp $

XORG_VERSION_CURRENT = (((7) * 10000000) + ((7) * 100000) + ((0) * 1000) + 0)
RELEASE_VERSION = RELEASE-1

AFB_DEFS = -DUSE_AFB

DRIVERSDKDIR = $(USRLIBDIR)/Server
DRIVERSDKMODULEDIR = $(USRLIBDIR)/Server/modules
DRIVERSDKINCLUDEDIR = $(USRLIBDIR)/Server/include

       XF86SRC = $(SERVERSRC)/hw/xfree86
    XF86COMSRC = $(XF86SRC)/common
 XF86PARSERSRC = $(XF86SRC)/parser
     XF86OSSRC = $(XF86SRC)/os-support
 XF86DRIVERSRC = $(XF86SRC)/drivers
     DRIVERSRC = $(XF86DRIVERSRC)

        XFREE86DOCDIR = $(DOCDIR)
      XFREE86PSDOCDIR = $(DOCPSDIR)
     XFREE86PDFDOCDIR = $(DOCPDFDIR)
    XFREE86HTMLDOCDIR = $(DOCHTMLDIR)
XFREE86JAPANESEDOCDIR = $(DOCDIR)/Japanese

# $Xorg: xf86.rules,v 1.3 2000/08/17 19:41:48 cpqbld Exp $

# $XFree86: xc/config/cf/xf86.rules,v 3.34tsi Exp $

# ----------------------------------------------------------------------
# site-specific configuration parameters that go after
# the platform-specific parameters - edit site.def to change

# site:  $TOG: site.sample /main/r64_final/1 1998/02/05 16:28:49 kaleb $

# site:  $XFree86: xc/config/cf/site.def,v 3.24 2000/06/25 20:17:29 dawes Exp $

# ---------------------------------------------------------------------
# Imake rules for building libraries, programs, scripts, and data files
# rules:  $Xorg: Imake.rules,v 1.3 2000/08/17 19:41:46 cpqbld Exp $
# rules:  $XdotOrg: xc/config/cf/Imake.rules,v 1.8 2005/02/01 22:27:00 ajax Exp $
#
#
#
#
# rules:  $XFree86: xc/config/cf/Imake.rules,v 3.128 2003/11/15 03:25:17 dawes Exp $

 _NULLCMD_ = @ echo -n

X_BYTE_ORDER = X_LITTLE_ENDIAN

GLIDE2INCDIR =

GLIDE3INCDIR =

GLIDE3LIBNAME =

TKLIBNAME =

TKLIBDIR =

TCLLIBNAME =

TCLIBDIR =

          PATHSEP = /
            SHELL = /bin/sh

              TOP = .
      CURRENT_DIR = .

            IMAKE = imake
           DEPEND = makedepend
        MKDIRHIER = mkdir -p
          REVPATH = revpath
    EXPORTLISTGEN =
             RMAN = RmanCmd
     RMANBASENAME = rman
      RMANOPTIONS = RmanOptions
        CONFIGSRC = $(TOP)/config
         IMAKESRC = $(CONFIGSRC)/imake
        DEPENDSRC = $(CONFIGSRC)/makedepend

          INCROOT = /usr/X11R7/include
        USRLIBDIR = /usr/X11R7/lib
           VARDIR = /var
        VARLIBDIR = $(VARDIR)/lib
  SYSTEMUSRLIBDIR = /usr/lib
  SYSTEMUSRINCDIR = /usr/include
         SHLIBDIR = /usr/X11R7/lib
       LINTLIBDIR = $(USRLIBDIR)/lint
          MANPATH = /usr/X11R7/man
    MANSOURCEPATH = $(MANPATH)/cat
           MANDIR = $(MANSOURCEPATH)$(MANSUFFIX)
        LIBMANDIR = $(MANSOURCEPATH)$(LIBMANSUFFIX)
       FILEMANDIR = $(MANSOURCEPATH)$(FILEMANSUFFIX)
       MISCMANDIR = $(MANSOURCEPATH)$(MISCMANSUFFIX)
     DRIVERMANDIR = $(MANSOURCEPATH)$(DRIVERMANSUFFIX)
     LOGDIRECTORY = $(VARDIR)/log

        VARRUNDIR = $(VARDIR)/run

         VARDBDIR = $(VARDIR)/db

               AR = ar clq

# Nice try but useless: make will inherit BOOTSTRAPCFLAGS
# from  top Makefile
  BOOTSTRAPCFLAGS =

               CC = gcc
               AS = as

.SUFFIXES: .cc

              CXX = g++

          CXXFILT = c++filt

           CXXLIB = -lstdc++

    CXXDEBUGFLAGS = -O2 -fno-strict-aliasing
CXXDEPENDINCLUDES =
 CXXEXTRA_DEFINES =
CXXEXTRA_INCLUDES =
   CXXSTD_DEFINES = -DCSRG_BASED $(CXXPROJECT_DEFINES)
       CXXOPTIONS =
      CXXINCLUDES = $(INCLUDES) $(TOP_INCLUDES) $(CXXEXTRA_INCLUDES)
       CXXDEFINES = $(CXXINCLUDES) $(CXXSTD_DEFINES) $(THREADS_CXXDEFINES) $(DEFINES) $(CXXEXTRA_DEFINES)
         CXXFLAGS = $(CXXDEBUGFLAGS) $(CXXOPTIONS) $(THREADS_CXXFLAGS) $(CXXDEFINES)

         COMPRESS = compress
          GZIPCMD = gzip -n

              CPP = cpp $(STD_CPP_DEFINES)
           RAWCPP = cpp -undef $(STD_CPP_OPTIONS)
    PREPROCESSCMD = gcc -E $(STD_CPP_DEFINES)

          INSTALL = install
     INSTALLFLAGS = -c

               LD = ld

              LEX = lex
               M4 = m4
          M4FLAGS =
           LEXLIB = -ll
             YACC = yacc
           CCYACC = yacc

             LINT = lint

      LINTLIBFLAG = -C
         LINTOPTS = -axz
               LN = ln -s
             MAKE = make
               MV = mv -f
               CP = cp

           RANLIB = ranlib

  RANLIBINSTFLAGS =

               RM = rm -f
             PERL = perl
         PERLOPTS =
     PERLENVSETUP = env LC_ALL=C
        MANSUFFIX = 1
     LIBMANSUFFIX = 3
    FILEMANSUFFIX = 5
    MISCMANSUFFIX = 7
  DRIVERMANSUFFIX = 4
   ADMINMANSUFFIX = 8
     MANSRCSUFFIX = man
     MANNEWSUFFIX = _man
          MANDEFS = -D__apploaddir__=$(XAPPLOADDIR) -D__appmansuffix__=$(MANSUFFIX) -D__filemansuffix__=$(FILEMANSUFFIX) -D__libmansuffix__=$(LIBMANSUFFIX) -D__miscmansuffix__=$(MISCMANSUFFIX) -D__drivermansuffix__=$(DRIVERMANSUFFIX) -D__adminmansuffix__=$(ADMINMANSUFFIX) -D__projectroot__=$(PROJECTROOT) -D__xconfigfile__=$(XCONFIGFILE) -D__xconfigdir__=$(XCONFIGDIR) -D__xlogfile__=$(XLOGFILE) -D__xservername__=$(XSERVERNAME) $(XORGMANDEFS) $(VENDORMANDEFS)

   COMPRESSMANCMD = gzip -n

            TROFF = groff -Tps
            NROFF = nroff -Tlatin1

         MSMACROS = -ms
        MANMACROS = -man
              TBL = tbl
              EQN = eqn -Tps
             NEQN = neqn -Tlatin1
              COL = col
         COLFLAGS = -b

            MODCC = gcc

           MODCPP = cpp
        MODCFLAGS = $(CFLAGS)
            MODAS = as
       MODASFLAGS =

            MODLD = ld

       MODLDFLAGS =
MODLDCOMBINEFLAGS = -X -r
            MODAR = ar clq

        MODRANLIB = ranlib

     STD_INCLUDES =
  STD_CPP_OPTIONS = -traditional
  STD_CPP_DEFINES = -traditional  $(PROJECT_DEFINES)
      STD_DEFINES = -DCSRG_BASED $(PROJECT_DEFINES)
 EXTRA_LOAD_FLAGS = -Wl,-rpath,$(USRLIBDIRPATH)
  EXTRA_LDOPTIONS =
  EXTRA_LIBRARIES =
             TAGS = ctags

   PARALLELMFLAGS =

    SHAREDCODEDEF =
         SHLIBDEF =

     SHLIBLDFLAGS = -shared -Wl,-rpath,$(USRLIBDIRPATH) $(SHLIBGLOBALSFLAGS)

         NOSTDLIB = -nostdlib
     POSTNOSTDLIB = -Wl,-Bstatic -lgcc -Wl,-Bdynamic

         PICFLAGS = -fPIC

      CXXPICFLAGS = -fPIC

    PROTO_DEFINES = -DFUNCPROTO=15 -DNARROWPROTO

     INSTPGMFLAGS =

     INSTBINFLAGS = -m 0755
     INSTUIDFLAGS = -m 4711
     INSTLIBFLAGS = -m 0644
     INSTINCFLAGS = -m 0444
     INSTMANFLAGS = -m 0444
     INSTDATFLAGS = -m 0444
    INSTKMEMFLAGS = -m 4711

      PROJECTROOT = /usr/X11R7

      CDEBUGFLAGS = -O2 -fno-strict-aliasing
        CCOPTIONS =

      ALLINCLUDES = $(INCLUDES) $(EXTRA_INCLUDES) $(TOP_INCLUDES) $(INSTALLED_INCLUDES) $(STD_INCLUDES)
       ALLDEFINES = $(ALLINCLUDES) $(STD_DEFINES) $(PROTO_DEFINES) $(THREADS_DEFINES) $(MODULE_DEFINES) $(DEFINES) $(EXTRA_DEFINES)
           CFLAGS = $(CDEBUGFLAGS) $(CCOPTIONS) $(THREADS_CFLAGS) $(MODULE_CFLAGS) $(ALLDEFINES)
        LINTFLAGS = $(LINTOPTS) -DLINT $(ALLDEFINES) $(DEPEND_DEFINES)
         LDPRELIB = -L$(USRLIBDIR) $(INSTALLED_LIBS)
        LDPOSTLIB =
        LDOPTIONS = $(CDEBUGFLAGS) $(CCOPTIONS)  $(EXTRA_LDOPTIONS) $(THREADS_LDFLAGS) $(LOCAL_LDFLAGS) $(LDPRELIBS)
     CXXLDOPTIONS = $(CXXDEBUGFLAGS) $(CXXOPTIONS) $(EXTRA_LDOPTIONS) $(THREADS_CXXLDFLAGS) $(LOCAL_LDFLAGS) $(LDPRELIBS)

           LDLIBS = $(LDPOSTLIBS) $(THREADS_LIBS) $(SYS_LIBRARIES) $(EXTRA_LIBRARIES)

           CCLINK = $(CC)

          CXXLINK = $(CXX)

     LDSTRIPFLAGS = -x
   LDCOMBINEFLAGS = -X -r
      DEPENDFLAGS =
   DEPEND_DEFINES = -DUSE_MAKEDEPEND

# Not sure this belongs here
         TKLIBDIR =
         TKINCDIR =
        TKLIBNAME =
        TKLIBRARY = -L$(TKLIBDIR) -l$(TKLIBNAME)
        TCLLIBDIR =
        TCLINCDIR =
       TCLLIBNAME =
       TCLLIBRARY = -L$(TCLLIBDIR) -l$(TCLLIBNAME)

        MACROFILE = NetBSD.cf
           RM_CMD = $(RM)

    IMAKE_DEFINES =
   IMAKE_WARNINGS = -Wundef

         IRULESRC = $(CONFIGDIR)
        IMAKE_CMD = $(IMAKE) -DUseInstalled -I$(IRULESRC) $(IMAKE_DEFINES) 		    $(IMAKE_WARNINGS)

     ICONFIGFILES = $(IRULESRC)/Imake.tmpl $(IRULESRC)/X11.tmpl 			$(IRULESRC)/site.def $(IRULESRC)/$(MACROFILE) 			$(IRULESRC)/xfree86.cf $(IRULESRC)/xf86.rules $(IRULESRC)/xorgsite.def $(IRULESRC)/host.def $(EXTRA_ICONFIGFILES)

# $Xorg: X11.rules,v 1.4 2000/08/17 19:41:46 cpqbld Exp $

# $XFree86: xc/config/cf/X11.rules,v 1.6 2001/01/17 16:22:31 dawes Exp $

# ----------------------------------------------------------------------
# X Window System Build Parameters and Rules
# $XdotOrg: xc/config/cf/X11.tmpl,v 1.52 2005/09/22 23:54:18 alanc Exp $
# $Xorg: X11.tmpl,v 1.6 2000/08/17 19:41:46 cpqbld Exp $
#
#
#
#
# $XFree86: xc/config/cf/X11.tmpl,v 1.248 2004/02/16 04:07:37 dawes Exp $

XORGRELSTRING = `echo 7 7 0 | sed -e 's/ /./g' -e 's/^/Version\\\ /'`
  XORGMANNAME = X Version 11

STICKY_DEFINES = -DHAS_STICKY_DIR_BIT

FCHOWN_DEFINES = -DHAS_FCHOWN

# -----------------------------------------------------------------------
# X Window System make variables; these need to be coordinated with rules

             XTOP = $(TOP)
           BINDIR = /usr/X11R7/bin
     BUILDINCROOT = $(TOP)/exports
      BUILDINCDIR = $(BUILDINCROOT)/include
      BUILDINCTOP = ../..
      BUILDLIBDIR = $(TOP)/exports/lib
      BUILDLIBTOP = ../..
      BUILDBINDIR = $(TOP)/exports/bin
      BUILDBINTOP = ../..
   BUILDMODULEDIR = $(BUILDLIBDIR)/modules
     BUILDI18NDIR = $(BUILDLIBDIR)/locale
   BUILDMODULETOP = $(BUILDLIBTOP)/..
    XBUILDINCROOT = $(XTOP)/exports
     XBUILDINCDIR = $(XBUILDINCROOT)/include/X11
     XBUILDINCTOP = ../../..
     XBUILDBINDIR = $(XBUILDINCROOT)/bin
           INCDIR = $(INCROOT)
           ADMDIR = /var/log
           LIBDIR = /usr/X11R7/lib/X11
         SHAREDIR = /usr/X11R7/share/X11
       LIBEXECDIR = /usr/X11R7/libexec
        MODULEDIR = $(USRLIBDIR)/modules
   TOP_X_INCLUDES =
          XBINDIR = $(PROJECTROOT)/bin

       INSTSRCDIR = /usr/X11R7/src

        ETCX11DIR = /etc/X11

          CONFDIR = $(ETCX11DIR)

           DOCDIR = $(LIBDIR)/doc
       DOCHTMLDIR = $(DOCDIR)/html
         DOCPSDIR = $(DOCDIR)/PostScript
        DOCPDFDIR = $(DOCDIR)/PDF
          FONTDIR = /usr/X11R7/share/fonts/X11
      FONTROOTDIR = /usr/X11R7/share/fonts/X11
     ENCODINGSDIR = ${FONTROOTDIR}/encodings
         XINITDIR = $(LIBDIR)/xinit
           XDMDIR = $(LIBDIR)/xdm
        XDMVARDIR = $(VARLIBDIR)/xdm
           TWMDIR = $(LIBDIR)/twm
           XSMDIR = $(LIBDIR)/xsm
           NLSDIR = $(LIBDIR)/nls
       XLOCALEDIR = $(LIBDIR)/locale
      LBXPROXYDIR = $(LIBDIR)/lbxproxy
  PROXYMANAGERDIR = $(LIBDIR)/proxymngr
        XPRINTDIR = $(LIBDIR)/xserver
      XAPPLOADDIR = $(LIBDIR)/app-defaults
       FONTCFLAGS = -t

     INSTAPPFLAGS = $(INSTDATFLAGS)

              RGB = $(XBINDIR)/rgb
            FONTC = $(XBINDIR)/bdftopcf
      MKFONTSCALE = $(XBINDIR)/mkfontscale
        MKFONTDIR = $(XBINDIR)/mkfontdir
      MKHTMLINDEX = $(XBINDIR)/mkhtmlindex
          UCS2ANY = $(XBINDIR)/ucs2any
      BDFTRUNCATE = $(XBINDIR)/bdftruncate
     UCSMAPPREFIX = $(FONTDIR)/util/map-
       XCURSORGEN = $(XBINDIR)/xcursorgen

     HTMLINDEXCMD = HtmlIndexCmd

       DOCUTILSRC = $(XTOP)/doc/util
        CLIENTSRC = $(TOP)/clients
          DEMOSRC = $(TOP)/demos
       XDOCMACROS = $(DOCUTILSRC)/macros.t
       XIDXMACROS = $(DOCUTILSRC)/indexmacros.t
       PROGRAMSRC = $(TOP)/programs
           LIBSRC = $(XTOP)/lib
          FONTSRC = $(XTOP)/fonts
     ENCODINGSSRC = $(FONTSRC)/encodings
       INCLUDESRC = $(BUILDINCROOT)/include
      XINCLUDESRC = $(INCLUDESRC)/X11
        SERVERSRC = $(XTOP)/programs/Xserver
       CONTRIBSRC = $(XTOP)/../contrib
   UNSUPPORTEDSRC = $(XTOP)/unsupported
           DOCSRC = $(XTOP)/doc
           RGBSRC = $(XTOP)/programs/rgb
      BDFTOPCFSRC = $(PROGRAMSRC)/bdftopcf
     MKFONTDIRSRC = $(PROGRAMSRC)/mkfontdir
    FONTSERVERSRC = $(PROGRAMSRC)/xfs
       FONTINCSRC = $(XTOP)/include/fonts
        EXTINCSRC = $(XTOP)/include/extensions
      FTSOURCEDIR = FreeTypeSrcDir
        DRMSRCDIR = $(TOP)/extras/drm
       MESASRCDIR = $(TOP)/extras/Mesa
  OGLSAMPLESRCDIR = $(TOP)/extras/ogl-sample
        PSWRAPSRC = $(XTOP)/config/pswrap
     TRANSCOMMSRC = $(LIBSRC)/xtrans
   TRANS_INCLUDES = -I$(TRANSCOMMSRC)
 CONNECTION_FLAGS = -DTCPCONN -DUNIXCONN  $(STICKY_DEFINES) $(FCHOWN_DEFINES) -DIPv6
XTRANS_FAILDEFINES = -DFAIL_HARD

    VENDORMANNAME = X.Org
 VENDORMANVERSION = `echo 7 7 0 | sed -e 's/ /./g' -e 's/^/Version\\\ /'`
      XORGMANDEFS = -D__xorgversion__="\"$(XORGRELSTRING)\" \"$(XORGMANNAME)\""
    VENDORMANDEFS = -D__vendorversion__="$(VENDORMANVERSION) $(VENDORMANNAME)"
       VENDORNAME = The X.Org Foundation
  VENDORNAMESHORT = X.Org

 VENDORWEBSUPPORT = http://wiki.X.Org

VENDORSUPPORTDEFS = -D__VENDORDWEBSUPPORT__='"$(VENDORWEBSUPPORT)"'

      XKBDEFRULES = xorg
  XKBDEFRULESDEFS = -D__XKBDEFRULES__='"$(XKBDEFRULES)"'

     XCONFIGFILE = xorg.conf
      XCONFIGDIR = $(LIBDIR)
        XLOGFILE = Xorg
     XSERVERNAME = Xorg

       XENVLIBDIR = $(USRLIBDIR)
   CLIENTENVSETUP = LD_LIBRARY_PATH=$(XENVLIBDIR) XLOCALEDIR=$(BUILDLIBDIR)/locale

# $Xorg: bsdLib.tmpl,v 1.3 2000/08/17 19:41:47 cpqbld Exp $
# $XFree86: xc/config/cf/bsdLib.tmpl,v 3.23 2003/11/04 01:59:31 dawes Exp $

          XLIBSRC = $(LIBSRC)/X11

SOXLIBREV = 6.2
DEPXONLYLIB =
XONLYLIB =  -lX11

LINTXONLY = $(LINTLIBDIR)/llib-lX11.ln

      DEPXLIBONLY = $(DEPXONLYLIB)
         XLIBONLY = $(XONLYLIB)
     LINTXONLYLIB = $(LINTXONLY)

      XEXTLIBSRC = $(LIBSRC)/Xext

SOXEXTREV = 6.4
DEPEXTENSIONLIB =
EXTENSIONLIB =  -lXext

LINTEXTENSION = $(LINTLIBDIR)/llib-lXext.ln

LINTEXTENSIONLIB = $(LINTEXTENSION)
          DEPXLIB = $(DEPEXTENSIONLIB) $(DEPXONLYLIB)
             XLIB = $(EXTENSIONLIB) $(XONLYLIB)
         LINTXLIB = $(LINTXONLYLIB)

    XSSLIBSRC = $(LIBSRC)/Xss

SOXSSREV = 1.0
DEPXSSLIB =
XSSLIB =  -lXss

LINTXSS = $(LINTLIBDIR)/llib-lXss.ln

    XXF86MISCLIBSRC = $(LIBSRC)/Xxf86misc

SOXXF86MISCREV = 1.1
DEPXXF86MISCLIB =
XXF86MISCLIB =  -lXxf86misc

LINTXXF86MISC = $(LINTLIBDIR)/llib-lXxf86misc.ln

    XXF86VMLIBSRC = $(LIBSRC)/Xxf86vm

SOXXF86VMREV = 1.0
DEPXXF86VMLIB =
XXF86VMLIB =  -lXxf86vm

LINTXXF86VM = $(LINTLIBDIR)/llib-lXxf86vm.ln

    XXF86DGALIBSRC = $(LIBSRC)/Xxf86dga

SOXXF86DGAREV = 1.0
DEPXXF86DGALIB =
XXF86DGALIB =  -lXxf86dga

LINTXXF86DGA = $(LINTLIBDIR)/llib-lXxf86dga.ln

    XXF86RUSHLIBSRC = $(LIBSRC)/Xxf86rush

DEPXXF86RUSHLIB = $(USRLIBDIR)/libXxf86rush.a
XXF86RUSHLIB =  -lXxf86rush

LINTXXF86RUSH = $(LINTLIBDIR)/llib-lXxf86rush.ln

    XVLIBSRC = $(LIBSRC)/Xv

SOXVREV = 1.0
DEPXVLIB =
XVLIB =  -lXv

LINTXV = $(LINTLIBDIR)/llib-lXv.ln

    XVMCLIBSRC = $(LIBSRC)/XvMC

SOXVMCREV = 1.0
DEPXVMCLIB =
XVMCLIB =  -lXvMC

LINTXVMC = $(LINTLIBDIR)/llib-lXvMC.ln

    XINERAMALIBSRC = $(LIBSRC)/Xinerama

SOXINERAMAREV = 1.0
DEPXINERAMALIB =
XINERAMALIB =  -lXinerama

LINTXINERAMA = $(LINTLIBDIR)/llib-lXinerama.ln

    XRESLIBSRC = $(LIBSRC)/XRes

SOXRESREV = 1.0
DEPXRESLIB =
XRESLIB =  -lXRes

LINTXRES = $(LINTLIBDIR)/llib-lXRes.ln

    DMXLIBSRC = $(LIBSRC)/dmx

DEPDMXLIB = $(USRLIBDIR)/libdmx.a
DMXLIB =  -ldmx

LINTDMX = $(LINTLIBDIR)/llib-ldmx.ln

    DPSLIBSRC = $(LIBSRC)/dps

DEPDPSLIB = $(USRLIBDIR)/libdps.a
DPSLIB =  -ldps

LINTDPS = $(LINTLIBDIR)/llib-ldps.ln

    DPSTKLIBSRC = $(LIBSRC)/dpstk

DEPDPSTKLIB = $(USRLIBDIR)/libdpstk.a
DPSTKLIB =  -ldpstk

LINTDPSTK = $(LINTLIBDIR)/llib-ldpstk.ln

    PSRESLIBSRC = $(LIBSRC)/psres

DEPPSRESLIB = $(USRLIBDIR)/libpsres.a
PSRESLIB =  -lpsres

LINTPSRES = $(LINTLIBDIR)/llib-lpsres.ln

    GLULIBSRC = $(LIBSRC)/GLU

SOGLUREV = 1.3
DEPGLULIB =
GLULIB =  -lGLU

LINTGLU = $(LINTLIBDIR)/llib-lGLU.ln

    GLXLIBSRC = $(LIBSRC)/GL

SOGLREV = 1.2
DEPGLXLIB =
GLXLIB =  -lGL

LINTGLX = $(LINTLIBDIR)/llib-lGL.ln

    GLWIDGETSRC = $(LIBSRC)/GLw

SOGLWREV = 1.0
DEPGLWLIB =
GLWLIB =  -lGLw

LINTGLW = $(LINTLIBDIR)/llib-lGLw.ln

    XRENDERLIBSRC = $(LIBSRC)/Xrender

SOXRENDERREV = 1.2.2
DEPXRENDERLIB =
XRENDERLIB =  -lXrender

LINTXRENDER = $(LINTLIBDIR)/llib-lXrender.ln

    XRANDRLIBSRC = $(LIBSRC)/Xrandr

SOXRANDRREV = 2.0
DEPXRANDRLIB =
XRANDRLIB =  -lXrandr

LINTXRANDR = $(LINTLIBDIR)/llib-lXrandr.ln

    XFIXESLIBSRC = $(LIBSRC)/Xfixes

SOXFIXESREV = 3.0
DEPXFIXESLIB =
XFIXESLIB =  -lXfixes

LINTXFIXES = $(LINTLIBDIR)/llib-lXfixes.ln

   XDAMAGELIBSRC = $(LIBSRC)/Xdamage

SOXDAMAGEREV = 1.0
DEPXDAMAGELIB =
XDAMAGELIB =  -lXdamage

LINTXDAMAGE = $(LINTLIBDIR)/llib-lXdamage.ln

XCOMPOSITELIBSRC = $(LIBSRC)/Xcomposite

SOXCOMPOSITEREV = 1.0
DEPXCOMPOSITELIB =
XCOMPOSITELIB =  -lXcomposite

LINTXCOMPOSITE = $(LINTLIBDIR)/llib-lXcomposite.ln

XEVIELIBSRC = $(LIBSRC)/Xevie

SOXEVIEREV = 1.0
DEPXEVIELIB =
XEVIELIB =  -lXevie

LINTXEVIE = $(LINTLIBDIR)/llib-lXevie.ln

   XCURSORLIBSRC = $(LIBSRC)/Xcursor

SOXCURSORREV = 1.0.2
DEPXCURSORLIB =
XCURSORLIB =  -lXcursor

LINTXCURSOR = $(LINTLIBDIR)/llib-lXcursor.ln

   APPLEWMLIBSRC = $(LIBSRC)/apple

DEPAPPLEWMLIB = $(USRLIBDIR)/libAppleWM.a
APPLEWMLIB =  -lAppleWM

LINTAPPLEWM = $(LINTLIBDIR)/llib-lAppleWM.ln

   WINDOWSWMLIBSRC = $(LIBSRC)/windows

DEPWINDOWSWMLIB = $(USRLIBDIR)/libWindowsWM.a
WINDOWSWMLIB =  -lWindowsWM

LINTWINDOWSWM = $(LINTLIBDIR)/llib-lWindowsWM.ln

    XFONTCACHELIBSRC = $(LIBSRC)/Xfontcache

SOXFONTCACHEREV = 1.2
DEPXFONTCACHELIB =
XFONTCACHELIB =  -lXfontcache

LINTXFONTCACHE = $(LINTLIBDIR)/llib-lXfontcache.ln

         XAUTHSRC = $(LIBSRC)/Xau

SOXAUTHREV = 6.0
DEPXAUTHLIB =
XAUTHLIB =  -lXau

LINTXAUTH = $(LINTLIBDIR)/llib-lXau.ln

      XDMCPLIBSRC = $(LIBSRC)/Xdmcp

SOXDMCPREV = 6.0
DEPXDMCPLIB =
XDMCPLIB =  -lXdmcp

LINTXDMCP = $(LINTLIBDIR)/llib-lXdmcp.ln

           XMUSRC = $(LIBSRC)/Xmu

SOXMUREV = 6.2
DEPXMULIB =
XMULIB =  -lXmu

LINTXMU = $(LINTLIBDIR)/llib-lXmu.ln

           XMUUSRC = $(LIBSRC)/Xmuu

SOXMUUREV = 1.0
DEPXMUULIB =
XMUULIB =  -lXmuu

LINTXMUU = $(LINTLIBDIR)/llib-lXmuu.ln

       OLDXLIBSRC = $(LIBSRC)/oldX

SOOLDXREV = 6.0
DEPOLDXLIB =
OLDXLIB =  -loldX

LINTOLDX = $(LINTLIBDIR)/llib-loldX.ln

         XPLIBSRC = $(LIBSRC)/Xp

SOXPREV = 6.2
DEPXPLIB =
XPLIB =  -lXp

LINTXP = $(LINTLIBDIR)/llib-lXp.ln

       TOOLKITSRC = $(LIBSRC)/Xt

SOXTREV = 6.0
DEPXTOOLONLYLIB =
XTOOLONLYLIB =  -lXt

LINTXTOOLONLY = $(LINTLIBDIR)/llib-lXt.ln

      DEPXTOOLLIB = $(DEPXTOOLONLYLIB) $(DEPSMLIB) $(DEPICELIB)
         XTOOLLIB = $(XTOOLONLYLIB) $(SMLIB) $(ICELIB)
     LINTXTOOLLIB = $(LINTXTOOLONLYLIB)

       XALIBSRC = $(LIBSRC)/Xa

SOXAREV = 1.0
DEPXALIB =
XALIB =  -lXa

LINTXA = $(LINTLIBDIR)/llib-lXa.ln

       AWIDGETSRC = $(LIBSRC)/Xaw

SOXAWREV = 8.0
DEPXAWLIB =
XAWLIB =  -lXaw

LINTXAW = $(LINTLIBDIR)/llib-lXaw.ln

       AWIDGET7SRC = $(LIBSRC)/Xaw7

SOXAW7REV = 7.0
DEPXAW7LIB =
XAW7LIB =  -lXaw

LINTXAW7 = $(LINTLIBDIR)/llib-lXaw.ln

       AWIDGET6SRC = $(LIBSRC)/Xaw6

SOXAW6REV = 6.1
DEPXAW6LIB =
XAW6LIB =  -lXaw

LINTXAW6 = $(LINTLIBDIR)/llib-lXaw.ln

         XILIBSRC = $(LIBSRC)/Xi

SOXINPUTREV = 6.0
DEPXILIB =
XILIB =  -lXi

LINTXI = $(LINTLIBDIR)/llib-lXi.ln

      XTESTLIBSRC = $(LIBSRC)/Xtst

SOXTESTREV = 6.1
DEPXTESTLIB =
XTESTLIB =  -lXtst

LINTXTEST = $(LINTLIBDIR)/llib-lXtst.ln

DEPXBSDLIB = $(USRLIBDIR)/libXbsd.a
XBSDLIB =  -lXbsd

LINTXBSD = $(LINTLIBDIR)/llib-lXbsd.ln

           ICESRC = $(LIBSRC)/ICE

SOICEREV = 6.4
DEPICELIB =
ICELIB =  -lICE

LINTICE = $(LINTLIBDIR)/llib-lICE.ln

            SMSRC = $(LIBSRC)/SM

SOSMREV = 6.0
DEPSMLIB =
SMLIB =  -lSM

LINTSM = $(LINTLIBDIR)/llib-lSM.ln

           XKEYSRC = $(LIBSRC)/Xkey

SOXKEYREV = 6.0
DEPXKEYLIB =
XKEYLIB =  -lXkey

LINTXKEY = $(LINTLIBDIR)/llib-lXkey.ln

         FSLIBSRC = $(LIBSRC)/FS

SOFSREV = 6.0
DEPFSLIB =
FSLIB =  -lFS

LINTFS = $(LINTLIBDIR)/llib-lFS.ln

         FONTLIBSRC = $(LIBSRC)/font

SOFONTREV = 1.5
DEPFONTLIB =
FONTLIB = -L$(FREETYPELIBDIR) -L$(FONTLIBSRC)  -lXfont

LINTXFONT = $(LINTLIBDIR)/llib-lXfont.ln
#
SOFONTREV = 1.5
DEPXFONTLIB =
XFONTLIB =  -lXfont

LINTXFONT = $(LINTLIBDIR)/llib-lXfont.ln

     FONTSTUBLIBSRC = $(FONTLIBSRC)/stubs

DEPFONTSTUBLIB = $(USRLIBDIR)/libfntstubs.a
FONTSTUBLIB =  -lfntstubs

LINTFONTSTUB = $(LINTLIBDIR)/llib-lfntstubs.ln
         DEPFONTLIB = $(DEPXFONTLIB) $(DEPFONTSTUBLIB)
            FONTLIB = $(XFONTLIB) $(FONTSTUBLIB) $(FREETYPE2LIB)

         FONTENCLIBSRC = $(LIBSRC)/fontenc

SOFONTENCREV = 1.0
DEPXFONTENCLIB =
XFONTENCLIB =  -lfontenc

LINTXFONTENC = $(LINTLIBDIR)/llib-lfontenc.ln

          XPMLIBSRC = $(LIBSRC)/Xpm

SOXPMREV = 4.11
DEPXPMLIB =
XPMLIB =  -lXpm

LINTXPM = $(LINTLIBDIR)/llib-lXpm.ln

          FREETYPE2LIBSRC = $(LIBSRC)/freetype2

SOFREETYPE2REV = 9.0
DEPFREETYPE2LIB =
FREETYPE2LIB =  -lfreetype

LINTFREETYPE2 = $(LINTLIBDIR)/llib-lfreetype.ln

FREETYPE2INCDIR=$(INCDIR)

FREETYPE2INCLUDES = -I$(FREETYPE2INCDIR) -I$(FREETYPE2INCDIR)/freetype2 -I$(FREETYPE2INCDIR)/freetype2/config

FREETYPE2DEFINES = -DFREETYPE2

          EXPATLIBSRC = $(LIBSRC)/expat

SOEXPATREV = 4.0
DEPEXPATLIB =
EXPATLIB =  -lexpat

LINTEXPAT = $(LINTLIBDIR)/llib-lexpat.ln

EXPATINCLUDES=$(TOP_X_INCLUDES)
EXPATDEFINES=-DEXPAT

          XFT1LIBSRC = $(LIBSRC)/Xft1

SOXFT1REV = 1.1
DEPXFT1LIB =
XFT1LIB =  -lXft

LINTXFT1 = $(LINTLIBDIR)/llib-lXft.ln

          XFTLIBSRC = $(LIBSRC)/Xft

SOXFTREV = 2.1.2
DEPXFTLIB =
XFTLIB =  -lXft

LINTXFT = $(LINTLIBDIR)/llib-lXft.ln

          FONTCONFIGLIBSRC = $(LIBSRC)/fontconfig

SOFONTCONFIGREV = 1.0.4
DEPFONTCONFIGLIB =
FONTCONFIGLIB =  -lfontconfig

LINTFONTCONFIG = $(LINTLIBDIR)/llib-lfontconfig.ln

FONTCONFIGINCDIR=$(INCDIR)

FONTCONFIGINCLUDES = -I$(FONTCONFIGINCDIR)

FCCACHE = $(BINDIR)/fc-cache

FONTCONFIGDEFINES = -DFONTCONFIG

XFTINCLUDES=$(FONTCONFIGINCLUDES) $(FREETYPE2INCLUDES)

LIBPNGINCDIR = /usr/include

LIBPNGINC=

LIBPNGDIR = /usr
LIBPNGLIBDIR = /usr/lib
LIBPNGINCDIR = /usr/include

LIBPNGLIB = -lpng

    XKBFILELIBSRC = $(LIBSRC)/xkbfile

SOXKBFILEREV =  1.0
DEPXKBFILELIB =
XKBFILELIB =  -lxkbfile

LINTXKBFILE = $(LINTLIBDIR)/llib-lxkbfile.ln

     XKBCOMPCMD = $(XBINDIR)/xkbcomp

    XKBUILIBSRC = $(LIBSRC)/xkbui

SOXKBUIREV =  1.0
DEPXKBUILIB =
XKBUILIB =  -lxkbui

LINTXKBUI = $(LINTLIBDIR)/llib-lxkbui.ln

EXTRAXAWREQS =

EXTRAXAWCLIENTDEPLIBS =

EXTRAXAWCLIENTLIBS =

        XTRAPLIBSRC = $(LIBSRC)/XTrap

SOXTRAPREV = 6.4
DEPXTRAPLIB =
XTRAPLIB =  -lXTrap

LINTXTRAP = $(LINTLIBDIR)/llib-lXTrap.ln

          DEPLIBS = $(DEPXAWLIB) $(DEPXMULIB) $(DEPXTOOLLIB) $(DEPXLIB)

         DEPLIBS1 = $(DEPLIBS)
         DEPLIBS2 = $(DEPLIBS)
         DEPLIBS3 = $(DEPLIBS)
         DEPLIBS4 = $(DEPLIBS)
         DEPLIBS5 = $(DEPLIBS)
         DEPLIBS6 = $(DEPLIBS)
         DEPLIBS7 = $(DEPLIBS)
         DEPLIBS8 = $(DEPLIBS)
         DEPLIBS9 = $(DEPLIBS)
         DEPLIBS10 = $(DEPLIBS)

       FCPRELOADPATTERN = libfontconfig.so.?

      XFTPRELOADPATTERN = libXft.so.?
  XRENDERPRELOADPATTERN = libXrender.so.?
    XFONTPRELOADPATTERN = libXfont*.so.?

XMULIBONLY = -lXmu
XMULIB = $(XMULIBONLY) $(XTOOLLIB) $(XLIB)

        CONFIGDIR = $(LIBDIR)/config

    USRLIBDIRPATH = $(USRLIBDIR)
        LDPRELIBS = -L$(USRLIBDIR)  $(INSTALLED_LIBS)
       LDPOSTLIBS =
     TOP_INCLUDES = -I$(INCROOT) $(TOP_X_INCLUDES)
  PROJECT_DEFINES =
   VENDOR_DEFINES = -DXVENDORNAME='"$(VENDORNAME)"' -DXVENDORNAMESHORT='"$(VENDORNAMESHORT)"'

CXXPROJECT_DEFINES =

# ----------------------------------------------------------------------
# start of Imakefile

MGCSFXDIR = $(LIBDIR)

MGCSFX = -DMGCSFXDIR=\"$(MGCSFXDIR)\"

JPEG = -DDOJPEG
JPEGDIR = jpeg
LIBJPEG = $(JPEGDIR)/libjpeg.a
JPEGINCLUDE = -I$(JPEGDIR)

TIFF = -DDOTIFF
TIFFDIR = tiff
LIBTIFF = $(TIFFDIR)/libtiff.a
TIFFINCLUDE = -I$(TIFFDIR)

PNG = -DDOPNG
PNGDIR = png
LIBPNG = $(PNGDIR)/libpng.a zlib/libz.a
PNGINCLUDE = -I$(PNGDIR)

PDS = -DDOPDS

SYS_LIBRARIES=        -lm

DEPLIBS = $(LIBJPEG) $(LIBTIFF) $(LIBPNG)
LOCAL_LIBRARIES = $(XLIB) $(DEPLIBS)

DEFINES= $(SCO) $(UNIX) $(NODIRENT) $(VPRINTF) $(TIMERS) 	$(HPUX7) $(JPEG) $(TIFF) $(PNG) $(PDS) $(DXWM) $(RAND) 	$(BACKING_STORE) $(BSDTYPES) $(SGI) $(MGCSFX) -DDOCDIR=\"/usr/share/man\" -Wno-error=implicit-function-declaration -Wno-error=implicit-int -Wno-error=int-conversion -Wno-error=incompatible-pointer-types

INCLUDES = $(JPEGINCLUDE) $(TIFFINCLUDE) $(PNGINCLUDE)

SRCS1 =	xv.c xvevent.c xvroot.c xvmisc.c xvimage.c xvcolor.c xvsmooth.c 	xv24to8.c xvgif.c xvpm.c xvinfo.c xvctrl.c xvscrl.c xvalg.c 	xvgifwr.c xvdir.c xvbutt.c xvpbm.c xvxbm.c xvgam.c xvbmp.c 	xvdial.c xvgraf.c xvsunras.c xvjpeg.c xvps.c xvpopup.c xvdflt.c 	xvtiff.c xvtiffwr.c xvpds.c xvrle.c xviris.c xvgrab.c vprintf.c 	xvbrowse.c xvtext.c xvpcx.c xviff.c xvtarga.c xvxpm.c xvcut.c 	xvxwd.c xvfits.c xvpng.c xvzx.c xvwbmp.c xvpcd.c 	xvmag.c xvpic.c xvmaki.c xvpi.c xvpic2.c xvvd.c xvmgcsfx.c 	xvml.c

OBJS1 =	xv.o xvevent.o xvroot.o xvmisc.o xvimage.o xvcolor.o xvsmooth.o 	xv24to8.o xvgif.o xvpm.o xvinfo.o xvctrl.o xvscrl.o xvalg.o 	xvgifwr.o xvdir.o xvbutt.o xvpbm.o xvxbm.o xvgam.o xvbmp.o 	xvdial.o xvgraf.o xvsunras.o xvjpeg.o xvps.o xvpopup.o xvdflt.o 	xvtiff.o xvtiffwr.o xvpds.o xvrle.o xviris.o xvgrab.o vprintf.o 	xvbrowse.o xvtext.o xvpcx.o xviff.o xvtarga.o xvxpm.o xvcut.o 	xvxwd.o xvfits.o xvpng.o xvzx.o xvwbmp.o xvpcd.o 	xvmag.o xvpic.o xvmaki.o xvpi.o xvpic2.o xvvd.o xvmgcsfx.o 	xvml.o

SRCS2=	bggen.c
OBJS2=	bggen.o

SRCS3=	vdcomp.c
OBJS3=	vdcomp.o

SRCS4=	xcmap.c
OBJS4=	xcmap.o

SRCS5=	xvpictoppm.c
OBJS5=	xvpictoppm.o

PROGRAMS= xv bggen vdcomp xcmap xvpictoppm

all::
	@echo ""
	@echo "  Did you remember to 'make depend' first?"
	@echo ""

       SUBDIRS = tiff

all::
	@echo "  building xv ..."
	@echo ""

$(LIBJPEG):
	cd $(JPEGDIR); $(MAKE) libjpeg.a

cleandir::
	@echo ""
	@echo "  cleaning in $(JPEGDIR) ..."
	@echo ""
	( cd $(JPEGDIR) ; $(MAKE) cleandir )
	@echo ""

$(LIBTIFF):
	cd $(TIFFDIR); $(MAKE) libtiff.a

cleandir::
	@echo "  cleaning in $(TIFFDIR) ..."
	@echo ""
	( cd $(TIFFDIR) ; $(MAKE) cleandir )
	@echo ""

SRCS = $(SRCS1) $(SRCS2) $(SRCS3) $(SRCS4)

all:: $(PROGRAMS)

depend:: .depend

.depend::
	$(RM) $@
	$(DEPEND) -f- $(DEPENDFLAGS) -- $(ALLDEFINES) $(DEPEND_DEFINES) -- $(SRCS) > $@

depend::
	@for flag in ${MAKEFLAGS} ''; do \
	  case "$$flag" in *=*) ;; --*) ;; *[ik]*) set +e;; esac; done; \
	for i in $(SUBDIRS) ;\
	do \
		echo "depending" "in $(CURRENT_DIR)/$$i..."; \
		(cd $$i && $(MAKE) $(MFLAGS) $(PARALLELMFLAGS) \
			 depend); \
	done

xv: $(OBJS1) $(DEPLIBS)
	$(RM) $@
	$(CCLINK) -o $@ $(LDOPTIONS) $(OBJS1) $(LOCAL_LIBRARIES) $(LDLIBS)  $(EXTRA_LOAD_FLAGS)

cleandir::
	$(RM) xv

bggen: $(OBJS2) $(DEPLIBS)
	$(RM) $@
	$(CCLINK) -o $@ $(LDOPTIONS) $(OBJS2) $(LOCAL_LIBRARIES) $(LDLIBS)  $(EXTRA_LOAD_FLAGS)

cleandir::
	$(RM) bggen

xcmap: $(OBJS4) $(DEPLIBS)
	$(RM) $@
	$(CCLINK) -o $@ $(LDOPTIONS) $(OBJS4) $(LOCAL_LIBRARIES) $(LDLIBS)  $(EXTRA_LOAD_FLAGS)

cleandir::
	$(RM) xcmap

xvpictoppm: $(OBJS5) $(DEPLIBS)
	$(RM) $@
	$(CCLINK) -o $@ $(LDOPTIONS) $(OBJS5) $(LOCAL_LIBRARIES) $(LDLIBS)  $(EXTRA_LOAD_FLAGS)

cleandir::
	$(RM) xvpictoppm

install:: xv
	@if [ -d $(DESTDIR)$(BINDIR) ]; then \
		set +x; \
	else \
		if [ -h $(DESTDIR)$(BINDIR) ]; then \
			(set -x; rm -f $(DESTDIR)$(BINDIR)); \
		fi; \
		(set -x; $(MKDIRHIER) $(DESTDIR)$(BINDIR)); \
	fi
	$(INSTALL) $(INSTALLFLAGS) $(INSTPGMFLAGS)  xv $(DESTDIR)$(BINDIR)/xv

install:: bggen
	@if [ -d $(DESTDIR)$(BINDIR) ]; then \
		set +x; \
	else \
		if [ -h $(DESTDIR)$(BINDIR) ]; then \
			(set -x; rm -f $(DESTDIR)$(BINDIR)); \
		fi; \
		(set -x; $(MKDIRHIER) $(DESTDIR)$(BINDIR)); \
	fi
	$(INSTALL) $(INSTALLFLAGS) $(INSTPGMFLAGS)  bggen $(DESTDIR)$(BINDIR)/bggen

install:: xcmap
	@if [ -d $(DESTDIR)$(BINDIR) ]; then \
		set +x; \
	else \
		if [ -h $(DESTDIR)$(BINDIR) ]; then \
			(set -x; rm -f $(DESTDIR)$(BINDIR)); \
		fi; \
		(set -x; $(MKDIRHIER) $(DESTDIR)$(BINDIR)); \
	fi
	$(INSTALL) $(INSTALLFLAGS) $(INSTPGMFLAGS)  xcmap $(DESTDIR)$(BINDIR)/xcmap

install:: xvpictoppm
	@if [ -d $(DESTDIR)$(BINDIR) ]; then \
		set +x; \
	else \
		if [ -h $(DESTDIR)$(BINDIR) ]; then \
			(set -x; rm -f $(DESTDIR)$(BINDIR)); \
		fi; \
		(set -x; $(MKDIRHIER) $(DESTDIR)$(BINDIR)); \
	fi
	$(INSTALL) $(INSTALLFLAGS) $(INSTPGMFLAGS)  xvpictoppm $(DESTDIR)$(BINDIR)/xvpictoppm

vdcomp: $(OBJS3) $(DEPLIBS)
	$(RM) $@
	$(CCLINK) -o $@ $(LDOPTIONS) $(OBJS3) $(LOCAL_LIBRARIES) $(LDLIBS)  $(EXTRA_LOAD_FLAGS)

cleandir::
	$(RM) vdcomp

install:: vdcomp
	@if [ -d $(DESTDIR)$(BINDIR) ]; then \
		set +x; \
	else \
		if [ -h $(DESTDIR)$(BINDIR) ]; then \
			(set -x; rm -f $(DESTDIR)$(BINDIR)); \
		fi; \
		(set -x; $(MKDIRHIER) $(DESTDIR)$(BINDIR)); \
	fi
	$(INSTALL) $(INSTALLFLAGS) $(INSTPGMFLAGS)  vdcomp $(DESTDIR)$(BINDIR)/vdcomp

all:: docs/xv.$(MANNEWSUFFIX)

docs/xv.$(MANNEWSUFFIX): docs/xv.$(MANSRCSUFFIX)
	$(RM) $@
	if test -z "$(PREPROCESSMANPAGES)" ; then \
	   cd `dirname docs/xv` && \
	   $(LN) `basename docs/xv.$(MANSRCSUFFIX)` `basename $@`; \
	else \
	      	     $(RAWCPP)  $(MANDEFS)  $(EXTRAMANDEFS) \
	     < docs/xv.$(MANSRCSUFFIX) | sed -e '/^#  *[0-9][0-9]*  *.*$$/d' 			-e '/^#line  *[0-9][0-9]*  *.*$$/d' 			-e '/^[ 	]*XCOMM$$/s/XCOMM/#/' 			-e '/^[ 	]*XCOMM[^a-zA-Z0-9_]/s/XCOMM/#/' 			-e '/^[ 	]*XHASH/s/XHASH/#/' 			-e '/\@\@$$/s/\@\@$$/\\/' >$@; \
	fi

cleandir::
	$(RM) docs/xv.$(MANNEWSUFFIX)

all:: docs/xv.0

docs/xv.0:: docs/xv.$(MANNEWSUFFIX)
	@if [ -f docs/xv.$(MANNEWSUFFIX) ]; \
	then \
	cat docs/xv.$(MANNEWSUFFIX) | $(NEQN) | $(TBL) | $(NROFF) $(MANMACROS) | $(COL) > docs/xv.0; \
	fi

install.man::
	@if [ -d $(DESTDIR)$(MANDIR) ]; then \
		set +x; \
	else \
		if [ -h $(DESTDIR)$(MANDIR) ]; then \
			(set -x; rm -f $(DESTDIR)$(MANDIR)); \
		fi; \
		(set -x; $(MKDIRHIER) $(DESTDIR)$(MANDIR)); \
	fi
	-@if [ -f docs/xv.0 ]; \
	then \
	$(INSTALL) -c $(INSTMANFLAGS) docs/xv.0 $(DESTDIR)$(MANDIR)/xv.0; \
	fi

cleandir::
	$(RM) docs/xv.0

all:: docs/bggen.$(MANNEWSUFFIX)

docs/bggen.$(MANNEWSUFFIX): docs/bggen.$(MANSRCSUFFIX)
	$(RM) $@
	if test -z "$(PREPROCESSMANPAGES)" ; then \
	   cd `dirname docs/bggen` && \
	   $(LN) `basename docs/bggen.$(MANSRCSUFFIX)` `basename $@`; \
	else \
	      	     $(RAWCPP)  $(MANDEFS)  $(EXTRAMANDEFS) \
	     < docs/bggen.$(MANSRCSUFFIX) | sed -e '/^#  *[0-9][0-9]*  *.*$$/d' 			-e '/^#line  *[0-9][0-9]*  *.*$$/d' 			-e '/^[ 	]*XCOMM$$/s/XCOMM/#/' 			-e '/^[ 	]*XCOMM[^a-zA-Z0-9_]/s/XCOMM/#/' 			-e '/^[ 	]*XHASH/s/XHASH/#/' 			-e '/\@\@$$/s/\@\@$$/\\/' >$@; \
	fi

cleandir::
	$(RM) docs/bggen.$(MANNEWSUFFIX)

all:: docs/bggen.0

docs/bggen.0:: docs/bggen.$(MANNEWSUFFIX)
	@if [ -f docs/bggen.$(MANNEWSUFFIX) ]; \
	then \
	cat docs/bggen.$(MANNEWSUFFIX) | $(NEQN) | $(TBL) | $(NROFF) $(MANMACROS) | $(COL) > docs/bggen.0; \
	fi

install.man::
	@if [ -d $(DESTDIR)$(MANDIR) ]; then \
		set +x; \
	else \
		if [ -h $(DESTDIR)$(MANDIR) ]; then \
			(set -x; rm -f $(DESTDIR)$(MANDIR)); \
		fi; \
		(set -x; $(MKDIRHIER) $(DESTDIR)$(MANDIR)); \
	fi
	-@if [ -f docs/bggen.0 ]; \
	then \
	$(INSTALL) -c $(INSTMANFLAGS) docs/bggen.0 $(DESTDIR)$(MANDIR)/bggen.0; \
	fi

cleandir::
	$(RM) docs/bggen.0

all:: docs/xcmap.$(MANNEWSUFFIX)

docs/xcmap.$(MANNEWSUFFIX): docs/xcmap.$(MANSRCSUFFIX)
	$(RM) $@
	if test -z "$(PREPROCESSMANPAGES)" ; then \
	   cd `dirname docs/xcmap` && \
	   $(LN) `basename docs/xcmap.$(MANSRCSUFFIX)` `basename $@`; \
	else \
	      	     $(RAWCPP)  $(MANDEFS)  $(EXTRAMANDEFS) \
	     < docs/xcmap.$(MANSRCSUFFIX) | sed -e '/^#  *[0-9][0-9]*  *.*$$/d' 			-e '/^#line  *[0-9][0-9]*  *.*$$/d' 			-e '/^[ 	]*XCOMM$$/s/XCOMM/#/' 			-e '/^[ 	]*XCOMM[^a-zA-Z0-9_]/s/XCOMM/#/' 			-e '/^[ 	]*XHASH/s/XHASH/#/' 			-e '/\@\@$$/s/\@\@$$/\\/' >$@; \
	fi

cleandir::
	$(RM) docs/xcmap.$(MANNEWSUFFIX)

all:: docs/xcmap.0

docs/xcmap.0:: docs/xcmap.$(MANNEWSUFFIX)
	@if [ -f docs/xcmap.$(MANNEWSUFFIX) ]; \
	then \
	cat docs/xcmap.$(MANNEWSUFFIX) | $(NEQN) | $(TBL) | $(NROFF) $(MANMACROS) | $(COL) > docs/xcmap.0; \
	fi

install.man::
	@if [ -d $(DESTDIR)$(MANDIR) ]; then \
		set +x; \
	else \
		if [ -h $(DESTDIR)$(MANDIR) ]; then \
			(set -x; rm -f $(DESTDIR)$(MANDIR)); \
		fi; \
		(set -x; $(MKDIRHIER) $(DESTDIR)$(MANDIR)); \
	fi
	-@if [ -f docs/xcmap.0 ]; \
	then \
	$(INSTALL) -c $(INSTMANFLAGS) docs/xcmap.0 $(DESTDIR)$(MANDIR)/xcmap.0; \
	fi

cleandir::
	$(RM) docs/xcmap.0

all:: docs/xvp2p.$(MANNEWSUFFIX)

docs/xvp2p.$(MANNEWSUFFIX): docs/xvp2p.$(MANSRCSUFFIX)
	$(RM) $@
	if test -z "$(PREPROCESSMANPAGES)" ; then \
	   cd `dirname docs/xvp2p` && \
	   $(LN) `basename docs/xvp2p.$(MANSRCSUFFIX)` `basename $@`; \
	else \
	      	     $(RAWCPP)  $(MANDEFS)  $(EXTRAMANDEFS) \
	     < docs/xvp2p.$(MANSRCSUFFIX) | sed -e '/^#  *[0-9][0-9]*  *.*$$/d' 			-e '/^#line  *[0-9][0-9]*  *.*$$/d' 			-e '/^[ 	]*XCOMM$$/s/XCOMM/#/' 			-e '/^[ 	]*XCOMM[^a-zA-Z0-9_]/s/XCOMM/#/' 			-e '/^[ 	]*XHASH/s/XHASH/#/' 			-e '/\@\@$$/s/\@\@$$/\\/' >$@; \
	fi

cleandir::
	$(RM) docs/xvp2p.$(MANNEWSUFFIX)

all:: docs/xvp2p.0

docs/xvp2p.0:: docs/xvp2p.$(MANNEWSUFFIX)
	@if [ -f docs/xvp2p.$(MANNEWSUFFIX) ]; \
	then \
	cat docs/xvp2p.$(MANNEWSUFFIX) | $(NEQN) | $(TBL) | $(NROFF) $(MANMACROS) | $(COL) > docs/xvp2p.0; \
	fi

install.man::
	@if [ -d $(DESTDIR)$(MANDIR) ]; then \
		set +x; \
	else \
		if [ -h $(DESTDIR)$(MANDIR) ]; then \
			(set -x; rm -f $(DESTDIR)$(MANDIR)); \
		fi; \
		(set -x; $(MKDIRHIER) $(DESTDIR)$(MANDIR)); \
	fi
	-@if [ -f docs/xvp2p.0 ]; \
	then \
	$(INSTALL) -c $(INSTMANFLAGS) docs/xvp2p.0 $(DESTDIR)$(MANDIR)/xvpictoppm.0; \
	fi

cleandir::
	$(RM) docs/xvp2p.0

all:: docs/vdcomp.$(MANNEWSUFFIX)

docs/vdcomp.$(MANNEWSUFFIX): docs/vdcomp.$(MANSRCSUFFIX)
	$(RM) $@
	if test -z "$(PREPROCESSMANPAGES)" ; then \
	   cd `dirname docs/vdcomp` && \
	   $(LN) `basename docs/vdcomp.$(MANSRCSUFFIX)` `basename $@`; \
	else \
	      	     $(RAWCPP)  $(MANDEFS)  $(EXTRAMANDEFS) \
	     < docs/vdcomp.$(MANSRCSUFFIX) | sed -e '/^#  *[0-9][0-9]*  *.*$$/d' 			-e '/^#line  *[0-9][0-9]*  *.*$$/d' 			-e '/^[ 	]*XCOMM$$/s/XCOMM/#/' 			-e '/^[ 	]*XCOMM[^a-zA-Z0-9_]/s/XCOMM/#/' 			-e '/^[ 	]*XHASH/s/XHASH/#/' 			-e '/\@\@$$/s/\@\@$$/\\/' >$@; \
	fi

cleandir::
	$(RM) docs/vdcomp.$(MANNEWSUFFIX)

all:: docs/vdcomp.0

docs/vdcomp.0:: docs/vdcomp.$(MANNEWSUFFIX)
	@if [ -f docs/vdcomp.$(MANNEWSUFFIX) ]; \
	then \
	cat docs/vdcomp.$(MANNEWSUFFIX) | $(NEQN) | $(TBL) | $(NROFF) $(MANMACROS) | $(COL) > docs/vdcomp.0; \
	fi

install.man::
	@if [ -d $(DESTDIR)$(MANDIR) ]; then \
		set +x; \
	else \
		if [ -h $(DESTDIR)$(MANDIR) ]; then \
			(set -x; rm -f $(DESTDIR)$(MANDIR)); \
		fi; \
		(set -x; $(MKDIRHIER) $(DESTDIR)$(MANDIR)); \
	fi
	-@if [ -f docs/vdcomp.0 ]; \
	then \
	$(INSTALL) -c $(INSTMANFLAGS) docs/vdcomp.0 $(DESTDIR)$(MANDIR)/vdcomp.0; \
	fi

cleandir::
	$(RM) docs/vdcomp.0

install:: xv_mgcsfx.sample
	@if [ -d $(DESTDIR)$(MGCSFXDIR) ]; then \
		set +x; \
	else \
		if [ -h $(DESTDIR)$(MGCSFXDIR) ]; then \
			(set -x; rm -f $(DESTDIR)$(MGCSFXDIR)); \
		fi; \
		(set -x; $(MKDIRHIER) $(DESTDIR)$(MGCSFXDIR)); \
	fi
	$(INSTALL) $(INSTALLFLAGS) $(INSTDATFLAGS) xv_mgcsfx.sample $(DESTDIR)$(MGCSFXDIR)/xv_mgcsfx.sample

tar:
	tar cf xv.tar Makefile* Imakefile *.c *.h bits docs 		 docs unsupt vms $(JPEGDIR) $(TIFFDIR) $(MISC)

# ----------------------------------------------------------------------
# common rules for all Makefiles - do not edit

.c.i:
	$(RM) $@
	 	$(CC) -E $(CFLAGS) $(_NOOP_) $*.c > $@

.SUFFIXES: .ii

.cc.ii:
	$(RM) $@
	 	$(CC) -E $(CFLAGS) $(_NOOP_) $*.cc > $@

.SUFFIXES: .s

.c.s:
	$(RM) $@
	 	$(CC) -S $(CFLAGS) $(_NOOP_) $*.c

.cc.s:
	$(RM) $@
	 	$(CC) -S $(CFLAGS) $(_NOOP_) $*.cc

emptyrule::

cleandir::
	$(RM) *.CKP *.ln *.BAK *.bak *.o core errs ,* *~ *.a .emacs_* tags TAGS make.log MakeOut *.core  "#"*

Makefile::
	-@if [ -f Makefile ]; then set -x; \
	$(RM) Makefile.bak; $(MV) Makefile Makefile.bak; \
	else exit 0; fi
	$(IMAKE_CMD) -DTOPDIR=$(TOP) -DCURDIR=$(CURRENT_DIR)

tags::
	$(TAGS) -w *.[ch]
	$(TAGS) -xw *.[ch] > TAGS

man_keywords::

html_index::

clean:: cleandir

distclean:: cleandir

# ----------------------------------------------------------------------
# rules for building in SUBDIRS - do not edit

install::
	@for flag in ${MAKEFLAGS} ''; do \
	  case "$$flag" in *=*) ;; --*) ;; *[ik]*) set +e;; esac; done; \
	for i in $(SUBDIRS) ;\
	do \
		echo "installing" "in $(CURRENT_DIR)/$$i..."; \
		(cd $$i && $(MAKE) $(MFLAGS) $(PARALLELMFLAGS) \
			DESTDIR=$(DESTDIR) install); \
	done

install.man::
	@for flag in ${MAKEFLAGS} ''; do \
	  case "$$flag" in *=*) ;; --*) ;; *[ik]*) set +e;; esac; done; \
	for i in $(SUBDIRS) ;\
	do \
		echo "installing man pages" "in $(CURRENT_DIR)/$$i..."; \
		(cd $$i && $(MAKE) $(MFLAGS) $(PARALLELMFLAGS) \
			DESTDIR=$(DESTDIR) install.man); \
	done

install.sdk::
	@for flag in ${MAKEFLAGS} ''; do \
	  case "$$flag" in *=*) ;; --*) ;; *[ik]*) set +e;; esac; done; \
	for i in $(SUBDIRS) ;\
	do \
		echo "installing driver SDK" "in $(CURRENT_DIR)/$$i..."; \
		(cd $$i && $(MAKE) $(MFLAGS) $(PARALLELMFLAGS) \
			DESTDIR='$(DESTDIR)' install.sdk); \
	done

clean::
	@for flag in ${MAKEFLAGS} ''; do \
	  case "$$flag" in *=*) ;; --*) ;; *[ik]*) set +e;; esac; done; \
	for i in $(SUBDIRS) ;\
	do \
		echo "cleaning" "in $(CURRENT_DIR)/$$i..."; \
		(cd $$i && $(MAKE) $(MFLAGS) $(PARALLELMFLAGS) \
			 clean); \
	done

tags::
	@for flag in ${MAKEFLAGS} ''; do \
	  case "$$flag" in *=*) ;; --*) ;; *[ik]*) set +e;; esac; done; \
	for i in $(SUBDIRS) ;\
	do \
		echo "tagging" "in $(CURRENT_DIR)/$$i..."; \
		(cd $$i && $(MAKE) $(MFLAGS) $(PARALLELMFLAGS) \
			TAGS='$(TAGS)' tags); \
	done

$(ONESUBDIR)/Makefile:
	@for flag in ${MAKEFLAGS} ''; do \
	  case "$$flag" in *=*) ;; --*) ;; *[n]*) executeit="no";; esac; done; \
	cd $(ONESUBDIR) && \
	if [ "$$executeit" != "no" ]; then \
		$(IMAKE_CMD) -DTOPDIR=$(IMAKETOP) -DCURDIR=$(ONECURDIR)$(ONESUBDIR); \
	fi;

Makefiles::
	-@for flag in ${MAKEFLAGS} ''; do \
	  case "$$flag" in *=*) ;; --*) ;; *[ik]*) set +e;; esac; done; \
	for flag in ${MAKEFLAGS} ''; do \
	  case "$$flag" in *=*) ;; --*) ;; *[n]*) executeit="no";; esac; done; \
	for i in $(SUBDIRS) ;\
	do \
		case "$(CURRENT_DIR)" in \
		.) curdir= ;; \
		*) curdir=$(CURRENT_DIR)/ ;; \
		esac; \
		echo "making Makefiles in $$curdir$$i..."; \
		itmp=`echo $$i | sed -e 's;^\./;;g' -e 's;/\./;/;g'`; \
		curtmp="$(CURRENT_DIR)" \
		toptmp=""; \
		case "$$itmp" in \
		    ../?*) \
			while echo "$$itmp" | grep '^\.\./' > /dev/null;\
			  do \
			     toptmp="/`basename $$curtmp`$$toptmp"; \
			     curtmp="`dirname $$curtmp`"; \
			     itmp="`echo $$itmp | sed 's;\.\./;;'`"; \
			  done \
		    ;; \
		esac; \
		case "$$itmp" in \
		*/?*/?*/?*/?*)	newtop=../../../../..;; \
		*/?*/?*/?*)	newtop=../../../..;; \
		*/?*/?*)	newtop=../../..;; \
		*/?*)		newtop=../..;; \
		*)		newtop=..;; \
		esac; \
		newtop="$$newtop$$toptmp"; \
		case "$(TOP)" in \
		/?*) imaketop=$(TOP) \
		     imakeprefix= ;; \
		.) imaketop=$$newtop \
		   imakeprefix=$$newtop/ ;; \
		*) imaketop=$$newtop/$(TOP) \
		   imakeprefix=$$newtop/ ;; \
		esac; \
		$(RM) $$i/Makefile.bak; \
		if [ -f $$i/Makefile ]; then \
			echo "	$(MV) Makefile Makefile.bak"; \
			if [ "$$executeit" != "no" ]; then \
				$(MV) $$i/Makefile $$i/Makefile.bak; \
			fi; \
		fi; \
		$(MAKE) $(MFLAGS) $(MAKE_OPTS) ONESUBDIR=$$i ONECURDIR=$$curdir IMAKETOP=$$imaketop IMAKEPREFIX=$$imakeprefix $$i/Makefile; \
		if [ -d $$i ] ; then \
			cd $$i; \
			$(MAKE) $(MFLAGS) Makefiles; \
			cd $$newtop; \
		else \
			exit 1; \
		fi; \
	done

includes::
	@for flag in ${MAKEFLAGS} ''; do \
	  case "$$flag" in *=*) ;; --*) ;; *[ik]*) set +e;; esac; done; \
	for i in $(SUBDIRS) ;\
	do \
		echo including "in $(CURRENT_DIR)/$$i..."; \
		(cd $$i && $(MAKE) $(MFLAGS) $(PARALLELMFLAGS) \
			 includes); \
	done

distclean::
	@for flag in ${MAKEFLAGS} ''; do \
	  case "$$flag" in *=*) ;; --*) ;; *[ik]*) set +e;; esac; done; \
	for i in $(SUBDIRS) ;\
	do \
		echo "cleaning" "in $(CURRENT_DIR)/$$i..."; \
		(cd $$i && $(MAKE) $(MFLAGS) $(PARALLELMFLAGS) \
			 distclean); \
	done

distclean::
	$(RM) Makefile .depend

# ----------------------------------------------------------------------
# dependencies generated by makedepend

# dependencies are in .depend

